version: "3.3"

services:
  nginx:
    container_name: 'nginx'
    image: 'nginx'
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme_challenge:/tmp/acme_challenge
    networks:
      - app
    restart: always
    depends_on:
     - webserver

  webserver:
    container_name: 'webserver'
    image: 'webserver'
    build:
      context: .
      dockerfile: webserver/Dockerfile
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/webserver
    volumes:
      - ./webserver:/webserver
    networks:
      - app
    ports:
      - 3000:3000
    restart: always
    command: node webserver/server.js
    depends_on:
      - mongodb

  mongodb:
    container_name: 'mongodb'
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
    networks:
      - app

volumes:
  dbdata6:


networks:
  app:
    driver: bridge